# Build Stage
FROM node:18-alpine AS build

# Shared folder setup
WORKDIR /app/shared
COPY ./shared ./
RUN npm ci

# Client setup
WORKDIR /app/client
COPY ./client ./
RUN npm ci

RUN npx tsc --noEmit
RUN npx vite build

# Production Stage
FROM nginx:stable-alpine

COPY --from=build /app/client/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
