# Build Stage
FROM node:18-alpine AS build

# Shared folder setup
WORKDIR /app/shared
COPY ./shared ./
RUN npm install

# Client setup
WORKDIR /app/client
COPY ./client ./
RUN npm install

RUN npx tsc --noEmit
RUN npx vite build

# Production Stage
FROM nginx:stable-alpine

COPY --from=build /app/client/dist /usr/share/nginx/html
COPY ./client/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
