import { Anim } from "../characters.types";

export const animFluppy: Record<string, Anim> = {
  UP: {
    start: 1,
    end: 4,
    zeroPad: 4,
    prefix: "fluppy/walk/up/",
    suffix: ".png",
    key: "fluppyUp",
  },
  RIGHT: {
    start: 1,
    end: 4,
    zeroPad: 4,
    prefix: "fluppy/walk/right/",
    suffix: ".png",
    key: "fluppyRight",
  },
  DOWN: {
    start: 1,
    end: 4,
    zeroPad: 4,
    prefix: "fluppy/walk/down/",
    suffix: ".png",
    key: "fluppyDown",
  },
  LEFT: {
    start: 1,
    end: 4,
    zeroPad: 4,
    prefix: "fluppy/walk/left/",
    suffix: ".png",
    key: "fluppyLeft",
  },
  IDLE_UP: {
    start: 1,
    end: 1,
    zeroPad: 4,
    prefix: "fluppy/walk/up_static/",
    suffix: ".png",
    key: "fluppyIdleUp",
  },
  IDLE_RIGHT: {
    start: 1,
    end: 1,
    zeroPad: 4,
    prefix: "fluppy/walk/right_static/",
    suffix: ".png",
    key: "fluppyIdleRight",
  },
  IDLE_DOWN: {
    start: 1,
    end: 14,
    zeroPad: 4,
    prefix: "fluppy/walk/down_static/",
    suffix: ".png",
    key: "fluppyIdleDown",
  },
  IDLE_LEFT: {
    start: 1,
    end: 1,
    zeroPad: 4,
    prefix: "fluppy/walk/left_static/",
    suffix: ".png",
    key: "fluppyIdleLeft",
  },
  ATTACK_UP: {
    start: 1,
    end: 4,
    zeroPad: 4,
    prefix: "fluppy/attack/up/",
    suffix: ".png",
    key: "fluppyUpAttack",
  },
  ATTACK_RIGHT: {
    start: 1,
    end: 4,
    zeroPad: 4,
    prefix: "fluppy/attack/right/",
    suffix: ".png",
    key: "fluppyRightAttack",
  },
  ATTACK_DOWN: {
    start: 1,
    end: 4,
    zeroPad: 4,
    prefix: "fluppy/attack/down/",
    suffix: ".png",
    key: "fluppyDownAttack",
  },
  ATTACK_LEFT: {
    start: 1,
    end: 4,
    zeroPad: 4,
    prefix: "fluppy/attack/left/",
    suffix: ".png",
    key: "fluppyLeftAttack",
  },
  HIT_UP: {
    start: 1,
    end: 6,
    zeroPad: 4,
    prefix: "fluppy/hit/up/",
    suffix: ".png",
    key: "fluppyUpHit",
  },
  HIT_RIGHT: {
    start: 1,
    end: 6,
    zeroPad: 4,
    prefix: "fluppy/hit/right/",
    suffix: ".png",
    key: "fluppyRightHit",
  },
  HIT_DOWN: {
    start: 1,
    end: 6,
    zeroPad: 4,
    prefix: "fluppy/hit/down/",
    suffix: ".png",
    key: "fluppyDownHit",
  },
  HIT_LEFT: {
    start: 1,
    end: 6,
    zeroPad: 4,
    prefix: "fluppy/hit/left/",
    suffix: ".png",
    key: "fluppyLeftHit",
  },
};
