export { animFluppy } from "./fluppy.anims";
export { animOneAir } from "./oneair.anims";
export { animTimothee } from "./timothee.anims";
export { animSlime } from "./slime.anims";
export { animWizard as animRobot } from "./robot.anims";
export { animWizard as animDino } from "./dino.anims";
export { animWizard as animGhost } from "./ghost.anims";
export { animWendy } from "./wendy.anims";
export { animJohn } from "./john.anims";
export { animLink } from "./link.anims";
