import { Anim } from "../characters.types";

export const animSlime: Record<string, Anim> = {
  UP: {
    start: 1,
    end: 6,
    zeroPad: 3,
    prefix: "slime/up",
    suffix: ".png",
    key: "slimeUp",
  },
  RIGHT: {
    start: 1,
    end: 6,
    zeroPad: 3,
    prefix: "slime/right",
    suffix: ".png",
    key: "slimeRight",
  },
  DOWN: {
    start: 1,
    end: 4,
    zeroPad: 3,
    prefix: "slime/down",
    suffix: ".png",
    key: "slimeDown",
  },
  LEFT: {
    start: 1,
    end: 6,
    zeroPad: 3,
    prefix: "slime/left",
    suffix: ".png",
    key: "slimeLeft",
  },
  IDLE: {
    start: 1,
    end: 8,
    zeroPad: 3,
    prefix: "slime/iddle",
    suffix: ".png",
    key: "slimeIdle",
  },
  IDLE_BACK: {
    start: 1,
    end: 4,
    zeroPad: 3,
    prefix: "slime/iddle-back",
    suffix: ".png",
    key: "slimeIdleBack",
  },
  ATTACK_UP: {
    start: 1,
    end: 7,
    zeroPad: 3,
    prefix: "slime/attack-up",
    suffix: ".png",
    key: "slimeUpAttack",
  },
  ATTACK_RIGHT: {
    start: 1,
    end: 7,
    zeroPad: 3,
    prefix: "slime/attack-right",
    suffix: ".png",
    key: "slimeRightAttack",
  },
  ATTACK_DOWN: {
    start: 1,
    end: 7,
    zeroPad: 3,
    prefix: "slime/attack-down",
    suffix: ".png",
    key: "slimeDownAttack",
  },
  ATTACK_LEFT: {
    start: 1,
    end: 7,
    zeroPad: 3,
    prefix: "slime/attack-left",
    suffix: ".png",
    key: "slimeLeftAttack",
  },
  HIT_UP: {
    start: 1,
    end: 3,
    zeroPad: 3,
    prefix: "slime/stun-up",
    suffix: ".png",
    key: "slimeUpHit",
  },
  HIT_RIGHT: {
    start: 1,
    end: 3,
    zeroPad: 3,
    prefix: "slime/stun-right",
    suffix: ".png",
    key: "slimeRightHit",
  },
  HIT_DOWN: {
    start: 1,
    end: 3,
    zeroPad: 3,
    prefix: "slime/stun-down",
    suffix: ".png",
    key: "slimeDownHit",
  },
  HIT_LEFT: {
    start: 1,
    end: 3,
    zeroPad: 3,
    prefix: "slime/stun-left",
    suffix: ".png",
    key: "slimeLeftHit",
  },
  DEAD: {
    start: 1,
    end: 5,
    zeroPad: 3,
    prefix: "slime/dead",
    suffix: ".png",
    key: "slimeDead",
  },
};
