import { Anim } from "../characters.types";

export const animTimothee: Record<string, Anim> = {
  UP: {
    start: 1,
    end: 6,
    zeroPad: 4,
    prefix: "timothee/up",
    suffix: ".png",
    key: "timotheeUp",
  },
  RIGHT: {
    start: 1,
    end: 6,
    zeroPad: 4,
    prefix: "timothee/right",
    suffix: ".png",
    key: "timotheeRight",
  },
  DOWN: {
    start: 1,
    end: 6,
    zeroPad: 4,
    prefix: "timothee/down",
    suffix: ".png",
    key: "timotheeDown",
  },
  LEFT: {
    start: 1,
    end: 6,
    zeroPad: 4,
    prefix: "timothee/left",
    suffix: ".png",
    key: "timotheeLeft",
  },
  IDLE_UP: {
    start: 1,
    end: 6,
    zeroPad: 4,
    prefix: "timothee/iddle-up",
    suffix: ".png",
    key: "timotheeIdleUp",
  },
  IDLE_RIGHT: {
    start: 1,
    end: 6,
    zeroPad: 4,
    prefix: "timothee/iddle-right",
    suffix: ".png",
    key: "timotheeIdleRight",
  },
  IDLE_DOWN: {
    start: 1,
    end: 6,
    zeroPad: 4,
    prefix: "timothee/iddle-down",
    suffix: ".png",
    key: "timotheeIdleDown",
  },
  IDLE_LEFT: {
    start: 1,
    end: 6,
    zeroPad: 4,
    prefix: "timothee/iddle-left",
    suffix: ".png",
    key: "timotheeIdleLeft",
  },
  ATTACK_UP: {
    start: 1,
    end: 4,
    zeroPad: 4,
    prefix: "timothee/attack-up",
    suffix: ".png",
    key: "timotheeUpAttack",
  },
  ATTACK_RIGHT: {
    start: 1,
    end: 4,
    zeroPad: 4,
    prefix: "timothee/attack-right",
    suffix: ".png",
    key: "timotheeRightAttack",
  },
  ATTACK_DOWN: {
    start: 1,
    end: 4,
    zeroPad: 4,
    prefix: "timothee/attack-down",
    suffix: ".png",
    key: "timotheeDownAttack",
  },
  ATTACK_LEFT: {
    start: 1,
    end: 4,
    zeroPad: 4,
    prefix: "timothee/attack-left",
    suffix: ".png",
    key: "timotheeLeftAttack",
  },
  DEAD: {
    start: 1,
    end: 3,
    zeroPad: 4,
    prefix: "timothee/dead",
    suffix: ".png",
    key: "timotheeDead",
  },
};
