import { Anim } from "../characters.types";

const animConfig: Record<string, Anim> = {
  UP: {
    start: 1,
    end: 4,
    zeroPad: 4,
    prefix: "oneair/walk/up/",
    suffix: ".png",
    key: "oneairUp",
  },
  RIGHT: {
    start: 1,
    end: 4,
    zeroPad: 4,
    prefix: "oneair/walk/right/",
    suffix: ".png",
    key: "oneairRight",
  },
  DOWN: {
    start: 1,
    end: 4,
    zeroPad: 4,
    prefix: "oneair/walk/down/",
    suffix: ".png",
    key: "oneairDown",
  },
  LEFT: {
    start: 1,
    end: 4,
    zeroPad: 4,
    prefix: "oneair/walk/left/",
    suffix: ".png",
    key: "oneairLeft",
  },
  IDLE_UP: {
    start: 1,
    end: 1,
    zeroPad: 4,
    prefix: "oneair/walk/up_static/",
    suffix: ".png",
    key: "oneairIdleUp",
  },
  IDLE_RIGHT: {
    start: 1,
    end: 1,
    zeroPad: 4,
    prefix: "oneair/walk/right_static/",
    suffix: ".png",
    key: "oneairIdleRight",
  },
  IDLE_DOWN: {
    start: 1,
    end: 14,
    zeroPad: 4,
    prefix: "oneair/walk/down_static/",
    suffix: ".png",
    key: "oneairIdleDown",
  },
  IDLE_LEFT: {
    start: 1,
    end: 1,
    zeroPad: 4,
    prefix: "oneair/walk/left_static/",
    suffix: ".png",
    key: "oneairIdleLeft",
  },
  ATTACK_UP: {
    start: 1,
    end: 4,
    zeroPad: 4,
    prefix: "oneair/attack/up/",
    suffix: ".png",
    key: "oneairUpAttack",
  },
  ATTACK_RIGHT: {
    start: 1,
    end: 4,
    zeroPad: 4,
    prefix: "oneair/attack/right/",
    suffix: ".png",
    key: "oneairRightAttack",
  },
  ATTACK_DOWN: {
    start: 1,
    end: 4,
    zeroPad: 4,
    prefix: "oneair/attack/down/",
    suffix: ".png",
    key: "oneairDownAttack",
  },
  ATTACK_LEFT: {
    start: 1,
    end: 4,
    zeroPad: 4,
    prefix: "oneair/attack/left/",
    suffix: ".png",
    key: "oneairLeftAttack",
  },
  HIT_UP: {
    start: 1,
    end: 6,
    zeroPad: 4,
    prefix: "oneair/hit/up/",
    suffix: ".png",
    key: "oneairUpHit",
  },
  HIT_RIGHT: {
    start: 1,
    end: 6,
    zeroPad: 4,
    prefix: "oneair/hit/right/",
    suffix: ".png",
    key: "oneairRightHit",
  },
  HIT_DOWN: {
    start: 1,
    end: 6,
    zeroPad: 4,
    prefix: "oneair/hit/down/",
    suffix: ".png",
    key: "oneairDownHit",
  },
  HIT_LEFT: {
    start: 1,
    end: 6,
    zeroPad: 4,
    prefix: "oneair/hit/left/",
    suffix: ".png",
    key: "oneairLeftHit",
  },
};

export default animConfig;
